pipeline {
    
    tools
    {
        maven 'maven391'
    }
    
  agent any
  
  environment
  {
      ARTIFACTORY_ACCESS_TOKEN = credentials('artifactory-jenkins-access-token')
      EC2_URL = 'ec2-user@ec2-13-231-183-32.ap-northeast-1.compute.amazonaws.com'
  }
  
  stages {
    stage('Build') {
      steps {
        sh 'cd calc && mvn clean install'
      }
    }
    stage('Test') {
      steps {
        sh 'cd calc && mvn test'
      }
      post {
        always {
          junit '*/**/*.xml'
        }
      }
    }
    
    stage('SonarQube Analysis') {
    //def mvn = tool 'Default Maven';
    steps{
    withSonarQubeEnv('SQ901') {
      sh "cd calc && mvn clean verify sonar:sonar -Dsonar.projectKey=jenkins-test-1 -Dsonar.projectName='jenkins-test-1'"
    }
    }
  }
    
    stage('Artifactory Upload') {
            steps {
                // configFileProvider([configFile(fileId: 'artifactory-jenkins-userpass')]) {
                    sh 'cd calc && mvn clean deploy '
                // }
            }
        }
        
    
    stage("docker build and run container")
    {
        steps
        {
            sh 'docker build -t tushar/docker-repo-prod ./calc/'
            sh 'docker stop docker-repo-jenkins1-prod || true'
            sh 'docker rm docker-repo-jenkins1-prod || true'
            sh 'docker run -d -p 4566:8080 --name docker-repo-jenkins1-prod tushar/docker-repo'
        }
    }
    
    stage("mail alert")
    {
        steps
        {
            mail bcc: '', body: '$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS', cc: '', from: '', replyTo: '', subject: '1$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!', to: 'tushar.bajaj@nagarro.com'
        }
    }
    
    }
}

