pipeline {
    
    tools
    {
        maven 'maven391'
    }
    
  agent any
  
  environment
  {
      ARTIFACTORY_ACCESS_TOKEN = credentials('artifactory-jenkins--toaccessken')
  }
  
  stages {
    stage('Build') {
      steps {
        sh 'cd calc && mvn clean install'
      }
    }
    stage('Test') {
      steps {
        sh 'cd calc && mvn test'
      }
      post {
        always {
          junit '*/**/*.xml'
        }
      }
    }
    
    stage('SonarQube Analysis') {
    //def mvn = tool 'Default Maven';
    steps{
    withSonarQubeEnv('SQ901') {
      sh "cd calc && mvn clean verify sonar:sonar -Dsonar.projectKey=jenkins-test-1 -Dsonar.projectName='jenkins-test-1'"
    }
    }
  }
    
    stage('Artifactory Upload') {
            steps {
                // configFileProvider([configFile(fileId: 'artifactory-jenkins-userpass')]) {
                    sh 'cd calc && mvn clean deploy '
                // }
            }
        }
        

    stage("docker build and run container")
    {
        steps
        {
            sh 'docker build -t docker-repo-dev ./calc/'
            sh 'docker stop docker-repo-jenkins1-dev || true'
            sh 'docker rm docker-repo-jenkins1-dev || true'
            sh 'docker run -d -p 4565:8080 --name docker-repo-jenkins1-dev tushar/docker-repo'
        }
    }
    
    stage("mail alert")
    {
        steps
        {
            emailext body: 'Test Message',
            subject: 'Test Subject',
            to: 'test@example.com'
        }
    }
    
    }
}
